# Generated by Django 4.2.16 on 2026-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='tracker_job_user_id_890174_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'applied_date'], name='tracker_job_user_id_0cb690_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', '-updated_at'], name='tracker_job_user_id_01e26e_idx'),
        ),
    ]
